title: Kimi's Blog!
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf
url: "http://kimheetae90.github.io"
baseurl : "/"
# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: kimheetae90

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
# hyvor_talk_website_id: 14
# google_analytics: UA-NNNNNNNN-N