# Site settings
title: KIMI Tech Blog
description: A blog about programming and development
baseurl: ""
url: "https://kimheetae90.github.io"

# User settings
username: Heetae Kim
user_description: Programmer
email: kimheetae90@kimheetae90.com
twitter_username: 
github_username:  kimheetae90
gplus_username:  kimheetae90
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
